parser: babel-eslint

extends:
  - eslint:recommended
  - prettier

env:
  amd: true
  browser: true
  es6: true
  mocha: true
  node: true
  serviceworker: true

# Rules in ESLint are grouped by category
#  All rules related to formatting or style are disabled,
#  because prettier.io supersedes them.
rules:

  # Possible Errors
  #  These rules relate to possible syntax or logic errors
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-prototype-builtins: error
  no-template-curly-in-string: error
  valid-jsdoc:
    - error
    -
      prefer:
        return: returns
      preferType:
        boolean: Boolean
        number: Number
        string: String
        array: Array
        object: Object
      requireReturn: false
      requireParamDescription: false
      requireReturnDescription: false
  no-console:
    - error
    - allow:
      - "warn"
      - "error"

  # Best Practices
  #  These rules relate to better ways of doing things to help you avoid problems
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity:
    - error
    - max: 5
  consistent-return: error
  default-case: error
  dot-notation: error
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers:
    - error
    - ignore: [-1, 0, 1]
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-warning-comments: error
  no-with: error
  prefer-promise-reject-errors:
    - error
    - allowEmptyReject: true
  radix: error
  require-await: error
  vars-on-top: error
  wrap-iife: error
  yoda: error

  # Strict Mode
  #  These rules relate to strict mode directives
  strict: error

  # Variables
  #  These rules relate to variable declarations
  init-declarations:
    - error
    - always
  no-catch-shadow: error
  no-label-var: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef-init: error
  no-undefined: error
  no-use-before-define: error

  # Node.js and CommonJS
  #  These rules relate to code running in Node.js, or in browsers with CommonJS
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error

  # ECMAScript 6
  #  These rules relate to ES6, also known as ES2015
  no-class-assign: error
  no-confusing-arrow: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  symbol-description: error
